version: '3'
services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'boilerplate-test'
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "5001:3000"
      - "5858:9229"
    environment:
      - NODE_ENV=test
      - MONGODB_CONNECTION=mongodb://mongodb:27017/tests
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./output/db:/data/db
      - ./output/logs:/data/logs
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/data/logs/mongo.logs