FROM node:8

ARG version=1.0.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm i -g mocha

COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .

RUN npm i

CMD ["mocha", "-r", "ts-node/register", "-r", "./tests/bootstrap.ts", "./tests/**/*-specs.ts", "--reporter", "spec"]
