FROM node:8

ARG version=1.0.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm i

COPY . .

RUN ./node_modules/.bin/tsc
RUN ./node_modules/.bin/babel --out-dir build build

CMD ["./node_modules/.bin/nodemon", "--watch", "src/**/*.ts", "--inspect=0.0.0.0:9229", "--exec", "./node_modules/.bin/ts-node", "./src/index.ts"]
